search_input = '//*[@id="search"]'
search_button = '//*[@id="search-icon-legacy"]'
search_filters_button = '//*[@aria-label="Search filters"]'
search_filter_this_month = '//*[contains(@title, "This month")]'
video_title = '//ytd-video-renderer//a[@id="video-title"]'
search_hidden_filter_collapse = '//*[@id="collapse" and @aria-hidden="true"]'
